global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'user1@mail.com,user2@mail.com'
    from: 'email_id@mail.com'
    smarthost: smtp.mail.com:587
    auth_username: 'email_id@mail.com'
    auth_identity: 'email_id@mail.com'
    auth_password: 'password'

templates:
      - 'template/email.tmpl' 
    # - 'template/wechat.tmpl' 