global:
  resolve_timeout: 20m

templates:
      - 'template/email.tmpl' 
    # - 'template/wechat.tmpl' 

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 10m
  repeat_interval:  10m
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'xxx@qq.com'
    send_resolved: true
    from: 'spacegate bot <alert@xxx>'
    smarthost:  smtp.xxx.com:465
    auth_username: 'alert@xxx'
    auth_password: 'xxx!'
    require_tls: false
    #html: '{{ template "email.html" }}' 
