global:
  resolve_timeout: 5m

templates:
      - 'template/email.tmpl' 
    # - 'template/wechat.tmpl' 

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 24h
  receiver: 'email'

receivers:
- name: 'email'
  email_configs:
  - to: 'user2@mail.com'
    send_resolved: true
    from: 'spacegate bot <space@token01.com>'
    smarthost: smtp.mail.com:587
    auth_username: 'email_id@mail.com'
    auth_identity: 'email_id@mail.com'
    auth_password: 'password'
    html: '{{ template "email.html" }}' 
